version: '3.9'

volumes:
  db_data:

services:
  apache:
    image: php:apache
    container_name: apache
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./web:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apache

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test
      MYSQL_USER: art
      MYSQL_PASSWORD: 123
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "8082:80"
    depends_on:
      - mysql
